/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Masaya SHIMOMURA' at '15/08/18 2:36' with Gradle 2.4
 *
 * @author Masaya SHIMOMURA, @date 15/08/18 2:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
